---
Name: elasticappsearch
---
SilverStripe\Search\Service\SearchService:
  index_variant: '`ENTERPRISE_SEARCH_ENGINE_PREFIX`'

SilverStripe\Core\Injector\Injector:
  SilverStripe\Search\Filter\CriteriaWriter:
    class: SilverStripe\Search\Filter\Niave\CriteriaWriter
  SilverStripe\Search\Filter\CriterionWriter:
    class: SilverStripe\Search\Filter\Niave\CriterionWriter
